### ISSUE TITLE
hello brother of good

### ISSUE THREAD

**Issue by glerinsonum** [t3ntman/CrunchRAT#1]
@t3ntman is there any video to implementation.

**Comment by t3ntman** [comment]
Unfortunately, there is not any video for setup. I can assist if you are having any issues though. Keep in mind that I have halted this project to work on a 2.0 version that has OS X and Windows capabilities.

**Comment by glerinsonum** [comment]
@t3ntman Thank you for your good work and for your response.

I have need for a video to see how is the use "configuration & installation" in the your works c#&php
I have no idea how i can implement with your works, because is complication.

**Comment by glerinsonum** [comment]
@t3ntman O Brother of Good. 
Make or Do the things easy easely, 
I'm not interesting about Remote Administration Tool, 
Is there any thing that is Internet Information Gather Grabber. 
Example 

python get_name.py -i ( id  of facebook ) ENTER

Connecting to facebook.... 
Searching this name by ID.... 
Found: Jim Jim ( 239293293923 ) 

python get_ip.py -i ( id of facebook ) Enter 
Connecting to facebook.... 
Searching address location by ID... 
Found: Jim Jim 2832832838232     Longitude: 2323232.232  Latitude: 232323232.2   IP: 1.1.1.1 by his ISP

:disappointed:

**Comment by t3ntman** [comment]
Closing this issue as this does not relate to anything with my RAT.
